### ISSUE TITLE
Request:  Composer/Packagist namespace ArchPHP

### ISSUE THREAD

**Issue by medmin** [GyanendroKh/ArchPHP-JWT#1]
Hi, Mr. Khomdram,

I am trying to publish a library to composer/packagist, but it shows the error message like the following, which means the `archphp` namespace has been taken and I need to get your permission to publish it.

> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at archphp

May I request that you add me to this namespace and give me maintainership access ?  Thanks.

I would really appreciate it.

Regards,

Yumin

**Comment by medmin** [comment]
I think maybe it is a similar case.
https://github.com/composer/packagist/issues/760

**Comment by GyanendroKh** [comment]
Yeah sure. [Email me](mailto:khgyanendrokh77@gmail.com) your username.
